# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 402b8f596b701b921b64886669f1ed83b1cd429e0499ca2e175036c24d732ee50dd034eb615432dbc1a5c8ff5ce3d196bd43259c4b4e732936cde273775c7af0

test:
  secret_key_base: cd89b3ff376ad4ec4c8e5534dd31eb353164199c871ca8a73b223b48838686468560448018ef3f493480bfd7c20be1b34f2d8b051d8c1a9142c11c50a786cc12 

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  url: <%= ENV["DB_URL"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
